.gitignore
AUTHORS
setup.py

Add .gitignore and setup.py

---

setup.py

Bump version to 0.2.7

---

README.rst
setup.py

I'd like to upload this package to the edX PyPI account. To prepare for that, I've made a few minor tweaks to the README and setup.py.
@nedbat @clintonb @jzoldak

Prepare package for distribution on PyPI

---

setup.py

@jzoldak @nedbat -- made the new v.0.2.8 tag before updating setup.py (whoops).  Doing things the correct way this time and bumping to v0.2.9

mattdrayer/increment-version: Bump to v0.2.9

---

README.rst
dev-requirements.txt
edx_lint/files/pylintrc
requirements.txt
setup.py

This reduces a lot of false negatives, especially for Django 1.8

Use pylint-django

---

edx_lint/files/pylintrc
pylintrc
setup.py
test/test_pylint_plugins.py

- Updated Pylint requirement
- Removed obsolete configuration options

Upgraded to Pylint 1.5.x

---

.coveragerc
.gitignore
.travis.yml
Makefile
dev-requirements.txt
edx_lint/cmd/check.py
edx_lint/cmd/list.py
edx_lint/cmd/main.py
edx_lint/cmd/write.py
edx_lint/pylint/__init__.py
edx_lint/pylint/getattr_check.py
edx_lint/pylint/i18n_check.py
edx_lint/pylint/module_trace.py
edx_lint/pylint/plugin.py
edx_lint/pylint/range_check.py
edx_lint/pylint/right_assert_check.py
edx_lint/pylint/super_check.py
edx_lint/tamper_evident.py
setup.py
test/test_pylint_plugins.py
test/test_tamper_evident.py
tox.ini

This changes the file operations back to pure byte strings.  Also, uses tox for testing, so we can easily test Python 2 and 3 locally.

Clean up, especially for Python 3

---

.gitignore
.travis.yml
setup.py

Deploy to PyPI

---

README.rst

@nedbat @clintonb @cpennington

Additional clarity for pylintrc_tweaks how-to.

---

edx_lint/pylint/layered_test_check.py
test/input/func_layered_tests.py

Move method out of the class that could be useful for future thing.  Booleanify the return value just in case. Add test cases to get coverage to 100%

Polish up layered_test_check

---

edx_lint/files/pylintrc
pylintrc
test/plugins/test_ignore_long_lines.py

Additionally ignore line-too-long for PII annotations

---

edx_lint/pylint/feature_toggle_check.py
edx_lint/pylint/getattr_check.py
edx_lint/pylint/i18n_check.py
edx_lint/pylint/layered_test_check.py
edx_lint/pylint/module_trace.py
edx_lint/pylint/range_check.py
edx_lint/pylint/right_assert_check.py
edx_lint/pylint/super_check.py
edx_lint/pylint/unicode_check.py
test/plugins/test_range_check.py
test/plugins/test_right_assert_check.py
test/plugins/test_super_check.py

I fixed some of the black things I didn't like.

---

edx_lint/pylint/getattr_check.py

Updated docstring to explain intension behind attribute literal quality check. Added few examples of alternatives.

Updated docstring for attribute literal check

---

.travis.yml
README.rst
setup.cfg
tox.ini

This already had tests in python 3.8 but now I am adding the classifiers

[BD-6] Add python 3.8 to the classifiers

---

edx_lint/cmd/amnesty.py
edx_lint/cmd/check.py
edx_lint/cmd/list.py
edx_lint/cmd/main.py
edx_lint/cmd/write.py
edx_lint/pylint/__init__.py
edx_lint/pylint/feature_toggle_check.py

Relevant JIRA issue [here](https://openedx.atlassian.net/browse/BOM-1793).

Removed deprecated future imports

---

CHANGELOG.rst
README.rst
edx_lint/__init__.py

**Issue:** [BOM-1848](https://openedx.atlassian.net/browse/BOM-1848)
- Added CHANGELOG
- Released new version `1.5.0`.

Add new Release

---

edx_lint/__init__.py

Bump the version.

---

edx_lint/__init__.py
edx_lint/files/common_constraints.txt

Revert "pytest-xdist latest version breaking tests. It needs to pin"

---

.github/ PULL_REQUEST_TEMPLATE.md
CHANGELOG.rst

* get changelog up to date since it was started.
* add PR template that reminds to update the changelog.
Post Merge:

clarify use of CHANGELOG.rst

---

edx_lint/__init__.py

Update version to 4.0.1

---

CHANGELOG.rst
edx_lint/__init__.py
edx_lint/pylint/unittest_assert/__init__.py
edx_lint/pylint/unittest_assert/unittest_assert_check.py
test/plugins/pylint_test.py
test/plugins/test_unittest_assert_check.py

JIRA:  https://openedx.atlassian.net/browse/BOM-2339

Added unittest assertion checker -- BOM-2339

---

edx_lint/files/common_constraints.txt

Add a note that changes to the common_constraints.txt file will
automatically be picked up, and doesn't require a new version
of edx-lint.

docs: update common_constraints.txt comments

---

edx_lint/files/common_constraints.txt

Relevant JIRA : https://openedx.atlassian.net/browse/BOM-2533

BOM-2533: Pin pyjwt in common contraints

---

edx_lint/files/common_constraints.txt

refactor: Django has fixed the file upload issue. Updating its constraint.
https://docs.djangoproject.com/en/3.2/releases/2.2.23/

refactor: Django has fixed the file upload issue. 

---

edx_lint/files/common_constraints.txt

Remove all pins related to PyJWT

feat: remove all pins related to PyJWT

---

CHANGELOG.rst
edx_lint/__init__.py

Update version to 5.2.0
**JIRA: (Optional)**
[XXX-XXXX](https://openedx.atlassian.net/browse/XXX-XXXX)

build: update version to 5.2.0

---

edx_lint/files/common_constraints.txt

Relax Django constraint in common_constraints.txt
[BOM-3030](https://openedx.atlassian.net/browse/BOM-3030)

chore: updating django pin to <3.3

---

edx_lint/files/common_constraints.txt

Update the Django common constraint as a part of the Django32 cleanup effort
**JIRA: [BOM-3237](https://openedx.atlassian.net/browse/BOM-3237)

chore: update Django constraint

---

CHANGELOG.rst
edx_lint/pylint/annotations_check.py
test/plugins/test_annotations_check.py

This is a part of https://github.com/openedx/public-engineering/issues/28

FC-0001: clean-up LegacyWaffle* linting

---

edx_lint/files/common_constraints.txt

fix: add desc for setuptools pin

---

edx_lint/pylint/module_trace.py
test/test_cmd.py

Describe in a couple of sentences what this PR adds
**JIRA: (Optional)**
[XXX-XXXX](https://openedx.atlassian.net/browse/XXX-XXXX)

style: silence two pylint warnings

---

edx_lint/__init__.py

- Bumping the package version to `5.3.4`.

chore: bump version 5.3.4

---

edx_lint/files/common_constraints.txt

feat: Constrain edx-drf-extensions until we fix our configs

---

edx_lint/files/common_constraints.txt

https://github.com/open-telemetry/opentelemetry-python/issues/3570 has been resolved
This PR closes the issue #407 

Unpin importlib_metadata 

---

edx_lint/__init__.py
edx_lint/files/common_constraints.txt

**Related Issue**
- https://github.com/openedx/edx-lint/issues/458

chore: add common constraint for pip
