openedx/edx-lint

- AUTHORS
- edx_lint/pylint/plugin.py
- edx_lint/pylint/right_assert_check.py
- test/input/func_asserts_check.py
- test/messages/func_asserts_check.txt
This is another Pylint checker that checks that comparisons aren't done inside of assertTrue/False, for example:
```
assertTrue(x == y) 
```
should be:
```
assertEqual(x, y)
```
I've started it here:
https://github.com/Sveder/custom-lints
and after email discussion with Ned Batchelder we agreed that it is a right fit to the edx-lint repo.
> New Checker for Renegade assertTrue/False

- edx_lint/files/pylintrc
Also, pin the ends of the regex to be stricter.
> Allow "class Meta" with no docstring.

- edx_lint/cmd/check.py
- edx_lint/cmd/list.py
- edx_lint/cmd/main.py
- edx_lint/cmd/write.py
- edx_lint/tamper_evident.py
@nedbat, @clintonb: I had to make these changes to make it so that the IDA cookiecutter could run in both python2 and python3 virtualenvs.
> Make edx-lint commands work with both python2 and python3

- .gitignore
- .travis.yml
- AUTHORS
- edx_lint/cmd/write.py
- setup.py
- test/test_cmd.py
> Python 3.5 fixes

- edx_lint/pylint/layered_test_check.py
- edx_lint/pylint/right_assert_check.py
- test/test_pylint_plugins.py
We had these deprecation warnings (among many others from inside pylint(!?)):
```
Warning: option required-attributes is obsolete and it is slated for removal in Pylint 1.6.
/src/edx/src/edx-lint/edx_lint/pylint/layered_test_check.py:44: PendingDeprecationWarning: locals is deprecated and will be removed in astroid 2.0, use the function 'get_locals()' instead.
dunder_test = node.locals.get("__test__")
/src/edx/src/edx-lint/edx_lint/pylint/right_assert_check.py:79: PendingDeprecationWarning: 'Getattr' is deprecated and slated for removal in astroid 2.0, use 'Attribute' instead
if not isinstance(node.func, astroid.Getattr):
```
> Remove deprecation warnings

- edx_lint/pylint/plugin.py
- edx_lint/pylint/required_base_class.py
- test/test_required_base_class.py
This adds a new checker, for required base classes.  A new setting, `required-base-class`, is a list of colon-separated pairs:
```
required-base-class: unittest.case.TestCase:common.tests.helpers.TestMixin, ....
```
This says that if a class derives from TestCase, then it must also derive from TestMixin.  The names must be fully qualified class names.  This is unfortunate in some cases, since like with unittest.case.TestCase, the fully qualified name does not correspond to how it was imported.
> Required base classes

- setup.py
I noticed we were several versions behind. For reference, here's Pylint's [changelog](https://pylint.readthedocs.io/en/latest/whatsnew/changelog.html).
@nedbat thoughts?
> Upgrade pylint to 1.6.4

- setup.py
It was released few days ago.
Also, I've had an issue with 1.6.4 incorrectly setting exit status to 0, while it should've actually been non-zero. So there may be some false-positives.
> Bump pylint to 1.6.5

- requirements.txt
We previously pinned pylint-django from 0.7.2 to 1.0.0. However, 0.8 has created dependency issues in repos that consume edx-lint. Since 0.7.2 is the only release prior to 0.8, I am explicitly pinning it until we have another solution.
> pin pylint-django-version

- edx_lint/cmd/write.py
- test/test_plugin_range_check.py
- test/utils.py
- tox.ini
Switching was easy.  Quieting the warnings was a journey through multiple levels of confusion, finally culminating in a blog post (linked from the tox.ini).
> Switch to pytest

- edx_lint/pylint/common.py
- edx_lint/pylint/required_base_class.py
- edx_lint/pylint/super_check.py
- requirements.txt
- test/plugins/test_required_base_class.py
- test/plugins/test_super_check.py
- tox.ini
Django has a setUpTestData method on its test cases that should also be checked for super() calls.  BTW, this is all I wanted to do, and it led to all of the recent edx-lint changes....!
> Check setUpTestData for super calls.

- .editorconfig
- edx_lint/files/.editorconfig
I want to get these rules into more repos.  First we need to agree on them.  Having them in edx-lint is a good way to get them into other repos.
@jmbowman @cpennington @georgebabey What do you think? Contrary opinions?
> Add more to the standard .editorconfig, and write our own

- .gitignore
- edx_lint/pylint/plugin.py
- edx_lint/pylint/yaml_load_check.py
- test/plugins/test_unicode_check.py
- test/plugins/test_yaml_load_check.py
https://nvd.nist.gov/vuln/detail/CVE-2017-18342
> In PyYAML before 4.1, the yaml.load() API could execute arbitrary code. In other words, yaml.safe_load is not used.
There's not a stable release beyond 3.13 yet (which is the version of `pyyaml` we're using), so let's go with this in the meantime?
> Add a check for unsafe yaml.load() calls.

- edx_lint/cmd/amnesty.py
- requirements.txt
@edx/incr-reviewers
> In your pull request, ask for a new release of edx-lint to be made once it is merged.
Initial attempt to simply update click-log in `requirements.txt` failed. 
Before changing `requirements.txt` I ran `tox` using the included `tox.ini`, I got failures for `py36-pylint{20,21}` environments and `pylint` environment. 
Current status: `tox` now passes for all but `pylint` but when I go into the `.tox` folder, activate the venv and run the pylint command it passes. I am currently baffled by this. 
when I run pytest using py37 it now passes (with Django and pytest installed)
reasons for other changes:
- pylint2.x.x requires specific versions of astroid installed based on pylint version. Later versions of astroid do not seem to have `astroid.YES`.  
- click-log >=2.0 no …
> INCR-4 :updated click-log and made py37 compliant

- .travis.yml
- tox.ini
[Travis are now recommending removing the __sudo__ tag](https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration).
"_If you currently specify __sudo: false__ in your __.travis.yml__, we recommend removing that configuration_"
pylint 2.x is required to support Python 3.7:
* http://pylint.pycqa.org/en/latest/whatsnew/changelog.html#what-s-new-in-pylint-2-0
> Travis CI: Remove sudo tag and add Python 3.7

- tox.ini
As discussed at https://github.com/edx/edx-lint/pull/93#issuecomment-467115234
> tox.ini: Legacy pylint raises StopIteration in Python 3.7

- edx_lint/files/pylintrc
- pylintrc
Turns out that removing this rule from enabled in earlier commit
wasn't good enough.
> add ungrouped-imports to disabled rule

- edx_lint/pylint/feature_toggle_check.py
- edx_lint/pylint/plugin.py
- edx_lint/pylint/unicode_check.py
- test/plugins/test_feature_toggle_check.py
Working off previous hackathon work by Robert: https://github.com/edx/edx-lint/pull/85. 
Documentation: https://openedx.atlassian.net/wiki/spaces/HACK/pages/940704078/Documenting+feature+toggles
Adds a linter for feature toggle annotations. The expectation is to have some documentation along the lines of [this example](https://github.com/edx/edx-platform/blob/d5ee03e81d06bfe067d51392d5827763992a3bba/lms/djangoapps/experiments/utils.py#L35-L50) for each feature toggle. There is at least one instance where we document a toggle with `documented_elsewhere`: [link to example](https://github.com/edx/edx-platform/blob/b9c7c10ca7416eeb8cff2181458b188378549d6b/cms/envs/common.py#L184), so I also accept that as valid documentation. 
To check this we simply look at the line above a toggle to make …
> Feature toggle annotation linter

- edx_lint/files/pylintrc
- pylintrc
The numeric score is meaningless and unactionable.
Also: pylint writes score output even if there are no violations.  I prefer the clean no-output look when everything passes.  Do some people like seeing the 10.00 score when everything is good?
> No need for numeric scores on pylint

- test/plugins/test_feature_toggle_check.py
flag_undefined_default has been deprecated and
is being removed, so remove it from the test.
ARCHBOM-1305
>  ARCHBOM-1305: remove flag_undefined_default

- edx_lint/files/common_constraints.txt
https://openedx.atlassian.net/browse/BOM-1867
Purpose of this file is to define a common constraint at one place and use it in all edx repos. e.g right now all edx repos using `django<2.3` but we have to mentioned it in all repos local constraint.txt file. But now you can just define the constraint in this file and call the path in ur desired edx repo constraint.txt like this 
`-c https://raw.githubusercontent.com/edx/edx-lint/84f463efed7f287a60eeb44cffa4884342066b2c/edx_lint/files/common_constraints.txt`
If you don't need the constraint version you can overwrite in local constraint file.
> Adding common constraint file for edx repos usage.

- edx_lint/__init__.py
- edx_lint/files/common_constraints.txt
pytest-xdist latest version breaking tests. It needs to pin in all repos.
> pytest-xdist latest version breaking tests. It needs to pin

- edx_lint/pylint/feature_toggle_check.py
- test/plugins/test_feature_toggle_check.py
The `documented_elsewhere` annotation is removed in
code-annotations>=0.9.0.
See PR: https://github.com/edx/code-annotations/pull/51
cc @robrap
> [BD-21] Get rid of deprecated "documented_elsewhere" annotation

- CHANGELOG.rst
- edx_lint/__init__.py
- requirements/base.in
- requirements/base.txt
- requirements/ci.in
- requirements/ci.txt
- requirements/constraints.txt
- requirements/dev.in
- requirements/dev.txt
- requirements/pip-tools.txt
- requirements/pip.txt
- requirements/test.in
- requirements/test.txt
**Issue:** [BOM-2261](https://openedx.atlassian.net/browse/BOM-2261)
- `base.in` had `Django<2.3` constraint which caused conflicts & hence [build failure](https://travis-ci.com/github/edx/edx-organizations/jobs/475385652) in Django30 & Django31 tests where this package is being used as a dependency. 
- Added `constraints.txt` file for pinning the versions which resolved the issue and [tests](https://github.com/edx/edx-organizations/pull/166) passed using this commit.
> Switch constraints to constraints.txt file

- CHANGELOG.rst
- edx_lint/__init__.py
- edx_lint/pylint/annotations_check.py
- test/plugins/test_annotations_check.py
Annotation checks did not define a line number, which caused all annotation
failures to be associated with line 1. This caused CI not to fail, despite some
linting issues. We resolve this by associating the annotation group line number
to the linting errors.
cc @robrap 
This should be ready to review.
> [BD-21] Fix line number in annotation checks

- edx_lint/files/common_constraints.txt
This needs to be pinned to resolve make upgrade conflicts in most of the services.
`drf-jwt` has pinned `PyJWT`: https://github.com/Styria-Digital/django-rest-framework-jwt/blob/612ba1e5f300477334c49c0fddaaac82b80f587a/setup.cfg#L39
> Pinned social-auth-core to resolve make upgrade conflicts

- CHANGELOG.rst
- edx_lint/__init__.py
- edx_lint/pylint/annotations_check.py
- requirements/base.txt
- requirements/constraints.txt
- requirements/dev.txt
- requirements/test.txt
- test/plugins/test_annotations_check.py
- test/plugins/test_ignore_long_lines.py
Previously, it was required to run `code_annotations --lint` in order to verify
code annotations. The errors then had to be collected manually, for instance
with a paver task. This made it intractable to generalize code annotation
checking to multiple IDAs. With this new checker, code annotation errors are
sent to pylint, which makes it easy for everyone to quickly detect annotation
errors. To achieve this, we make use of the new code annotations API created in
v1.1.0.
This PR depends on https://github.com/edx/code-annotations/pull/61 (:heavy_check_mark: merged)
cc @robrap
> [BD-21] Report generic code annotation errors

- CHANGELOG.rst
- edx_lint/__init__.py
- edx_lint/cmd/amnesty.py
edx-lint amnesty breaks when it runs into line continuations because it places the comment after the backslash.
Commit for reference:
https://github.com/edx/edx-platform/pull/26391/commits/4afb7c4dfc7005125f4abb3f3440e6b035d27559#diff-9105611e27bef349fe3153c23fdb4789e8c23f1503202e03e19bf14ef70415faR224
Went from:
```
log.warning('Error in conditional module: \
required module {module} has no {module_attr}'.format(module=module, module_attr=attr_name))
```
to
```
log.warning('Error in conditional module: \  # lint-amnesty, pylint: disable=logging-format-interpolation 
required module {module} has no {module_attr}'.format(module=module, module_attr=attr_name))
```
which becomes a syntax error.
This PR fixes the problem, now the amnesty will place the comment at the end of line properly like …
> BOM-2341 : Don't put amnesty on line continuation

- CHANGELOG.rst
- edx_lint/__init__.py
- edx_lint/pylint/annotations_check.py
- test/plugins/pylint_test.py
- test/plugins/test_annotations_check.py
- test/plugins/test_ignore_long_lines.py
This PR adds a linter for missing annotations. Here, we only lint (NonNamespaced)WaffleFlag/Switch objects for which the first argument is a string.
Note: this PR also fixes a few unit tests which broke down during the upgrade to pylint 2.6.0.
cc @robrap.
> [BD-21] Lint missing waffle annotations

- requirements/base.in
- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- requirements/test.txt
**JIRA Issue:** [BOM-2418](https://openedx.atlassian.net/browse/BOM-2418)
Removing the `Django` requirement from `base.in` because: 
- `Django` requirement in `base.in` causes the `django` version in [testeng-ci repo](https://github.com/edx/testeng-ci/blob/981773e6a419cc8347183624893c11cde11f93c0/requirements/testing.txt#L50) to upgrade to `django==3.1.6` which causes failures in different [jobs](https://build.testeng.edx.org/job/travis-job-counts/259251/console). 
- It upgrades the Django version to 3+ in any repo that uses this package without applying constraint on `Django` versions.
> Remove base django requirement

- edx_lint/files/common_constraints.txt
For docutils constraint, adds a link to the bug report.
> docs: add bug report link to constraint

- edx_lint/files/common_constraints.txt
The problem mentioned for constraint's reason is fixed in https://github.com/Styria-Digital/django-rest-framework-jwt/pull/91 , so we are unpinning it.
> BOM-2465: Unpin social-auth-core

- edx_lint/files/common_constraints.txt
**Issue:** [BOM-2482](https://openedx.atlassian.net/browse/BOM-2482)
- Pinning pylint version to resolve `pkginfo version check conflict` with pylint-django.
> BOM-2482: Pin pylint<2.8.0

- edx_lint/files/common_constraints.txt
- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- requirements/pip-tools.txt
- requirements/test.txt
**Issue:** [BOM-2496](https://openedx.atlassian.net/browse/BOM-2496)
- `pylint-django==2.4.4` fixed the `pkginfo.version` issue conflict between `pylint` & `pylint-django` so now the constraint can be removed.
> BOM-2496: remove pylint common constraint

- edx_lint/files/common_constraints.txt
**JIRA Issue:** [BOM-2513](https://openedx.atlassian.net/browse/BOM-2513)
`django==2.2.21` fixed a [security vulnerability](https://docs.djangoproject.com/en/3.2/releases/2.2.21/) by adding sanity checks for empty file paths for uploaded files.
This broke the tests hence pinning the version to fix the tests.
https://code.djangoproject.com/ticket/32718 is addressing this issue. 
This constraint will be removed once the tests has been fixed according to the advised solution.
> BOM-2513: Pin the django<2.2.21

- edx_lint/files/common_constraints.txt
- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- requirements/pip-tools.txt
- requirements/test.txt
click>=8.0.0 causes conflicts with Sphinx latest version in make upgrade job.
failing builds:
- https://github.com/edx/edx-django-utils/runs/2597892035?check_suite_focus=true
- https://github.com/edx/xss-utils/runs/2597405478?check_suite_focus=true
- https://github.com/edx/django-config-models/runs/2597212205?check_suite_focus=true
> fix: pin click<8.0 version

- edx_lint/files/common_constraints.txt
- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- requirements/pip-tools.txt
- requirements/test.txt
`Sphinx>=4.0.1` requires `Jinja2<3.0.0` and `MarkupSafe<2.0.0` which conflicts with latest package versions and causes following build failures: 
- https://build.testeng.edx.org/job/event-routing-backends-upgrade-python-requirements/31/console
- https://github.com/edx/edx-cookiecutters/runs/2598651286?check_suite_focus=true
Pinned jinja2 and MarkupSafe versions to resolve the issue.
`Sphinx==4.0.2` release is [in-queue](https://github.com/sphinx-doc/sphinx/issues/9214) right now. It can be removed once `Sphinx==4.0.2` is released.
> Pinned Jinja2 and MarkupSafe versions in common constraints

- edx_lint/files/common_constraints.txt
- requirements/base.txt
- requirements/dev.txt
- requirements/pip-tools.txt
- requirements/test.txt
**Issue:** [BOM-2547](https://openedx.atlassian.net/browse/BOM-2547)
- `Click`, `Jinja2` and `MarkupSafe` were pinned due to `Sphinx` conflict issue which has been fixed in the new `Sphinx==4.0.2` release.
> BOM-2547: Removed Sphinx related common constraints

- edx_lint/files/common_constraints.txt
An update to edx-sphinx-theme means we don't have to pin docutils
anymore: https://github.com/edx/edx-sphinx-theme/pull/111
We can merge this pull request once the edx-sphinx-theme pull request is merged, and a version pushed to PyPI.
> fix: no need to pin docutils

- edx_lint/files/common_constraints.txt
The constraints that block us from upgrading social-auth-core are part of the common constraints file. I am moving the social-auth-core constraint here as well to make it clear that there is a relationship.
> feat: Adding a constraint for social-auth-core that is caused by other common constraints

- edx_lint/files/common_constraints.txt
Add constraints to stop make upgrading from picking up
newer versions of libraries that require pyjwt 2.1.0
until we are ready for all services to upgrade.
> fix: add pyjwt related constraints

- edx_lint/files/common_constraints.txt
- elasticsearch>=7.14.0 includes breaking changes in it which caused issues in discovery upgrade process.
- elastic search changelog: https://www.elastic.co/guide/en/enterprise-search/master/release-notes-7.14.0.html
> fix: pin elasticsearch<7.14.0 version

- edx_lint/files/common_constraints.txt
- [PR](https://github.com/edx/edx-lint/pull/183) pinned elastic search package in common constraints but used the incorrect package name `elastic-search` so updating it with correct package name `elasticsearch`.
> fix: Use correct package name for pinning elasticsearch

- edx_lint/files/common_constraints.txt
Pytest have released 6.2.5 two days ago: release note : https://docs.pytest.org/en/6.2.x/changelog.html#pytest-6-2-5-2021-08-29
> fix: remove pluggy constraint 

- CHANGELOG.rst
- edx_lint/cmd/list.py
- edx_lint/cmd/main.py
- edx_lint/cmd/update.py
- edx_lint/write.py
- test/test_cmd.py
The "update" command will write any file that already exists.  It still checks that the existing file is a valid edx_lint-written file, so it won't destroy local edits.
> feat: a new "update" command.

- CHANGELOG.rst
- edx_lint/files/pylintrc
- pylintrc
- requirements/base.txt
- requirements/ci.txt
- requirements/constraints.txt
- requirements/dev.txt
- requirements/pip-tools.txt
- requirements/test.txt
- setup.py
- Remove our local pylint pin, so that we use the same version of pylint as everyone else
- Silence a new violation: "consider using an f-string".  This is not a problem that should fail builds.
- Fix one violation in setup.py
> build: update pylint, and the messages we disable

- .github/workflows/commitlint.yml
This syncs us up with edx/.github/workflows/commitlint.yml
> build: switch to common commitlint action from org template

- .github/workflows/commitlint.yml
This repo still had a full copy of the commitlint action instead of a reference to a reusable workflow.  This brings this repo into line with all the others.
> Use the central commitlint action

- edx_lint/files/common_constraints.txt
Empirical data has led us to rule out redis-py version 4 as the cause of some redis server instability.
We believe the instability is related to the lack of connection pooling in edx-platform and ecommerce.
See: https://openedx.atlassian.net/wiki/spaces/ENG/pages/3316580400/Redis+outage+-+technical+investigation#The-LMS-and-studio-celery-config-does-not-use-celery-connection-pooling
This reverts commit 210c2b2cdb29e0c65b1df0bb254defd321f4d9f9.
> Revert "fix: add common constraint of redis<4"

- .github/workflows/ci.yml
- CHANGELOG.rst
- Makefile
- edx_lint/__init__.py
- edx_lint/pylint/super_check.py
- requirements/base.txt
- requirements/dev.txt
- requirements/test.txt
- tox.ini
- Updated the import path of a protected pylint function `_ancestors_to_call()` to fix the breaking issue with `pylint==2.13.0`. 
- `pylint==2.13.0` refactored the `pylint.checkers.classes` module and moved the `_ancestors_to_call()` function from `pylint.checkers.classes.__init__.py` to `pylint.checkers.classes.checkers_classes.py`. See [PR](https://github.com/PyCQA/pylint/pull/5497) for details. 
- This caused the error with new `pylint==2.13.0` version across all edx repos in running `python requirements upgrade` job. 
- For now, only the module path is being updated but this piece of code should be removed/updated to remove this dependency on an internal function altogether.
> fix: fix import issues with pylint==2.13.0

- edx_lint/files/common_constraints.txt
- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- requirements/pip.in
- requirements/pip.txt
- requirements/test.txt
**Issue:** [BOM-3400](https://openedx.atlassian.net/browse/BOM-3400)
- pip-tools fails with latest pip==22.1 version. The failure details are in the issue https://github.com/jazzband/pip-tools/issues/1617.
> BOM-3400: Pin pip<22.1 in common constraints

- edx_lint/files/common_constraints.txt
- requirements/ci.txt
- requirements/dev.txt
- requirements/test.txt
**Issue:** [BOM-xxxx](https://openedx.atlassian.net/browse/BOM-xxxx)
- `django-simple-history>3.0.0` adds indexing and causes a lot of migrations to be affected. Indexing can be skipped by providing a custom argument from settings but it still updated a lot of meta attributes and causes the migrations to be updated. 
- The version will be pinned for now and the flag will be added in the required repos in separate repos.
- Then the version will be bumped later on after investigating all the needed changes and the best method to handle migrations update.
> fix: pin django-simple-history version

- edx_lint/files/common_constraints.txt
- requirements/base.txt
- requirements/dev.txt
- requirements/pip-tools.txt
- requirements/pip.txt
- requirements/test.txt
**Issue:** [BOM-3400](https://openedx.atlassian.net/browse/BOM-3400)
- `pip-tools==6.6.1` [resolved](https://github.com/jazzband/pip-tools/blob/master/CHANGELOG.md#661-2022-05-13) the compatibility issues with `pip>=22.1` so removed the pin from common constraints.
> BOM-3400: Remove pip common constraint

- .gitignore
- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- requirements/pip-tools.txt
- requirements/pip.txt
- requirements/test.txt
- Ran `make upgrade` locally to update `pip` to latest available version and resolve the failure occurring with scheduled requirements upgrade task.
> chore: upgrade requirements

- edx_lint/files/common_constraints.txt
Tox >4.0.0 has breaking changes and is causing CI to fail in all upgrade PRs. Description of the issue has been attached in constraints file.
> Pin tox to <4.0.0

- edx_lint/files/common_constraints.txt
- `edx-sphinx-theme` is not compatible with latest `Sphinx==6.0.0` version 
- Pinning Sphinx version unless the compatibility issue gets resolved
- For details, see issue https://github.com/openedx/edx-sphinx-theme/issues/197
> Add global Sphinx constraint

- edx_lint/files/common_constraints.txt
- `setuptools` had been pinned due to an issue in the pipelines. Details are mentioned in the issue https://github.com/edx/edx-arch-experiments/issues/150. 
- PR https://github.com/openedx/edx-platform/pull/31647 in edx-platform removed the `setuptools` constraint manually and the deployment was successful so we can now remove the common constraint for all the repos.
> fix: remove global setuptools constraint

- .github/workflows/ci.yml
- CHANGELOG.rst
- edx_lint/__init__.py
- edx_lint/pylint/super_check.py
- requirements/base.txt
- requirements/constraints.txt
- requirements/dev.txt
- requirements/pip.txt
- requirements/test.txt
- test/plugins/pylint_test.py
- test/plugins/test_super_check.py
- tox.ini
- `pylint<2.15` was constrained due to test failures previously due to breaking changes.
- Last release of `edx-lint==5.3.1` caused pylint version to be downgraded in multiple repos when the requirements upgrade workflow PRs were created because of this constraint. 
- Removed pylint constraint from `constraints.txt` & upgraded requirements.
- Updated tests for the build to pass with latest pylint version.
- Removed CI tests for older pylint versions.
- Bumped the version to `5.3.2`.
> Remove pylint constraint

- edx_lint/files/pylintrc
We're currently getting the following in pylint output:
pylint: Command line or configuration file:1: UserWarning: Specifying exception names in the overgeneral-exceptions option without module name is deprecated and support for it will be removed in pylint 3.0. Use fully qualified name (maybe 'builtins.Exception' ?) instead.
> fix: Be precise about the exception we're ignoring.

- CONTRIBUTING.rst
We now have a org wide CONTRIBUTING.md that points to our correct
general contributing guidelines.  We don't need repo specific ones that
forward to other contributing docs.
> docs: Remove repo specific CONTRIBUTING.rst

- Makefile
- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- requirements/pip.txt
- requirements/test.txt
Updated the Makefile `make upgrade` target to also upgrade `pip.txt` when the target is executed. 
It fixes the `pip` & `pip-tools` version conflict by upgrading `pip` since the latest `pip-tools>=6.13.0` requires `pip>=23.1.0` to work.
> fix: fix the make upgrade target to upgrade pip

- edx_lint/files/common_constraints.txt
Reverts openedx/edx-lint#342 -- we've fixed the base64 padding issues in 2U's configs.
See https://github.com/openedx/edx-drf-extensions/issues/346
> feat: Remove constraint on edx-drf-extensions<8.8.0

- edx_lint/files/common_constraints.txt
We no longer need this constraint because non of the repositories in
openedx use the `edx-sphinx-theme`.  The theme and extensions we use now
properly advertise their compatability and are maintained by a 3rd
party (sphinx-book-theme).
> build: Remove constraint on sphinx<6.0.0

- edx_lint/files/common_constraints.txt
- PR created under the issue https://github.com/openedx/edx-lint/issues/336 to remove the global tox constraint
- All the edx/openedx repositories have already been upgraded to remove the usage of tox-battery due to which the global constraint was being used.
> fix: remove global tox constraint

- edx_lint/files/common_constraints.txt
- With the removal of global constraint `tox<4.0`, now the tox requires `platformdirs==4.0` but virtualenv requires `platformdirs<4.0` which conflict and hence the requirements upgrade build fails for all repositories.
- Added the global constraint `platformdirs<4.0` to fix the failing requirements upgrade builds.
- This constraint can be removed once the new version of virtualenv is out and the issue https://github.com/pypa/virtualenv/issues/2666 is fixed. 
- Created followup issue https://github.com/openedx/edx-lint/issues/378 to remove this global constraint.
> fix: add global platformdirs constraint

- edx_lint/files/common_constraints.txt
This PR updates the Django common constraint used by other projects' repositories to use the latest LTS version: https://openedx.atlassian.net/wiki/spaces/AC/pages/3767926815/Django+4.2+Upgrade+Plan
> chore: update Django constraint to match latest LTS version

- edx_lint/files/common_constraints.txt
This will be needed for https://github.com/openedx/edx-django-utils/issues/389
> feat: Pin importlib-metadata globally for opentelemetry

- edx_lint/files/common_constraints.txt
Pins event-tracking to a version before installing pymongo 4.4.0 which is not supported on edx-platform.
See https://github.com/openedx/tutor-contrib-aspects/issues/891, https://github.com/openedx/event-routing-backends/pull/436, https://github.com/openedx/completion/pull/305 for more information.
> fix: pin event-tracking for pymongo 4.4.0 support

- CHANGELOG.rst
- edx_lint/__init__.py
- edx_lint/pylint/filters_docstring/__init__.py
- edx_lint/pylint/filters_docstring/filters_docstring_check.py
This PR adds a custom linter for Open edX Filter classes docstrings to check whether new filters follow the specified format: 
```
Description:
Filter used to modify the certificate rendering process.
... (more description)
Filter Type:
org.openedx.learning.certificate.render.started.v1
Trigger:
- Repository: openedx/edx-platform
- Path: lms/djangoapps/certificates/views/webview.py
- Function or Method: render_html_view
```
If a class is missing at least one of the section, then a pylint error is raised:
You can see the linter integrated into the repo in this PR: https://github.com/openedx/openedx-filters/pull/249
I'm open to moving this directly into the openedx-filters repo if needed, considering that the linter is kind of specific to that repository.
**Merge …
> feat: [FC-0074] add linter for Open edX Filters classes definitions

- edx_lint/files/commitlint.config.js
This moves `commitlint.config.js` from CJS syntax to MJS syntax. This is one part of the fix for https://github.com/openedx/.github/issues/163.  I have verified this works with the commitlint workflow in https://github.com/openedx/paragon/pull/3435.
> fix: update commitlint config to use mjs syntax

- edx_lint/files/commitlint.config.js
The default `commitlint` `header-max-length` (from `config-conventional`) is 100 characters. This is generally not a problem, but in situations where a PR is squashed the default GH web UI behavior appends ` (#X[...]X)` to the commit message header. This can cause commits that have landed to fail `commitlint`.
This PR just gives us a little wiggle room for those scenarios. 
> fix: increase commitlint header-max-length for squashed PR numbers

- CHANGELOG.rst
edx-toggles was moved to docs.openedx.org, so update the references.
> docs: Update edx.rtd links to docs.openedx.org

- edx_lint/files/common_constraints.txt
- fix: Don't pin django-simple-history
We removed this pin in edx-platform a while ago and if we can run these
migrations there, I think any other services should be able to handle
this as well.  Also there is no ticket with details here and so it is
not clear if there was a specific concern other than performance issues
with adding indexes.
Reference (default branch in edx-platform as of today):
https://github.com/openedx/edx-platform/blob/d29171c04649f29a26bfc96aa73b64bf01bfdd5b/Makefile#L124-L125
- fix: Drop the urllib3 constraint
Other updates seem to have resolved the issue reported when this was
pinned.  The issue there seems to be resolved in edx-platform now as
shown in https://github.com/openedx/edx-platform/pull/37059
Given that this was the only known issue with this, we can …
> Remove some old common constraints

- edx_lint/files/common_constraints.txt
A fix was made upstream
https://github.com/jazzband/pip-tools/issues/2131 and we confirmed it is
fine via https://github.com/openedx/edx-platform/pull/37309
Resolves https://github.com/openedx/edx-lint/issues/459
> fix: Drop pip constraint
